schema_version = "1.0.0"

id = "fusion_keys_navigation"
version = "0.5.8"
name = "Fusion 按键与导航"
tagline = "Fusion 360 风格鼠标导航、视图立方体和 Tab 模式菜单"
maintainer = "qwejun"
type = "add-on"

website = "https://github.com/qwejun/blender-fusion-navigation"

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
