schema_version = "1.0.0"

id = "fusion_keys_navigation"
version = "0.5.5"
name = "Fusion 按键与导航"
tagline = "Fusion 360 风格导航、视图和建模辅助菜单，参考 MACHIN3tools 交互"
maintainer = "qwejun"
type = "add-on"

website = "https://github.com/qwejun/blender-fusion-navigation"

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
